/**
 * Provides classes for configuration management.
 * <p>
 * The classes in this package are generated by JAXB and locally further modified. The
 * classes follow the data hierarchy in the XML-based configuration file validate by a
 * respective schema.
 */
package ch.rollis.emma.configuration;
